---
- hosts: 192.168.10.240
  become: yes
  become_method: sudo
  tasks: 
  - name: run hazelcast Container
    docker_container: 
      name: hazelcast
      image: hazelcast/hazelcast
      state: started
      exposed_ports:
      - 5701

